lo<?php
error_reporting(E_ALL);
ini_set('display_errors', '1');

include("manage_session.php");
set_time_limit(3000);

$time = microtime();
$time = explode(' ', $time);
$time = $time[1] + $time[0];
$header_start_time = $time;
$last_updated_date = date("Y-m-d H:i:s");

include("connection.php");
?>
<html>
<body style="font-size:0.7em">
<?php
try {
	$db = getConnection();
	
	include("customer_lookup.php");
	
	
	$sql = "
	CREATE TABLE `cse_imports` (
	  `import_id` int(11) NOT NULL AUTO_INCREMENT,
	  `dir` varchar(255) DEFAULT '',
	  `folder` varchar(45) DEFAULT NULL,
	  `sub_folder` varchar(45) DEFAULT NULL,
	  `filename` varchar(45) DEFAULT NULL,
	  `full_filename` varchar(255) DEFAULT '',
	  `processed` datetime DEFAULT '0000-00-00 00:00:00',
	  PRIMARY KEY (`import_id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;
	
	CREATE TABLE `cse_folders` (
	  `folders` longtext NOT NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;
	
	CREATE TABLE `cse_caseact` (
		`caseact_id` int(11) NOT NULL AUTO_INCREMENT,
		`TITLE` VARCHAR(255) NULL DEFAULT NULL ,
		`COST` VARCHAR(255) NULL DEFAULT NULL,
		`ACCESS` VARCHAR(255) NULL DEFAULT NULL,
		`ARAP` VARCHAR(255) NULL DEFAULT NULL,
		`OLE3STYLE` VARCHAR(255) NULL DEFAULT NULL ,
		`WORDSTYLE` VARCHAR(255) NULL DEFAULT NULL ,
		`FRMWIDTH` VARCHAR(255) NULL DEFAULT NULL ,
		`FRMHEIGHT` VARCHAR(255) NULL DEFAULT NULL , 
		`FRMTM` VARCHAR(255) NULL DEFAULT NULL ,
		`FRMBM` VARCHAR(255) NULL DEFAULT NULL ,
		`FRMLM` VARCHAR(255) NULL DEFAULT NULL ,
		`FRMRM` VARCHAR(255) NULL DEFAULT NULL ,
		`ORIENT` VARCHAR(255) NULL DEFAULT NULL ,
		`COPIES` VARCHAR(255) NULL DEFAULT NULL ,
		`TYPEACT` VARCHAR(255) NULL DEFAULT NULL ,
		`BISTYLE` VARCHAR(255) NULL DEFAULT NULL ,
		`BIFEE` VARCHAR(255) NULL DEFAULT NULL ,
		`BICOST` VARCHAR(255) NULL DEFAULT NULL ,
		`BIPMT` VARCHAR(255) NULL DEFAULT NULL ,
		`BILATEFEE` VARCHAR(255) NULL DEFAULT NULL ,
		`BICYCLE` VARCHAR(255) NULL DEFAULT NULL ,
		`BITIME` VARCHAR(255) NULL DEFAULT NULL ,
		`BIHOURRATE` VARCHAR(255) NULL DEFAULT NULL ,
		`BIPMTDATE` VARCHAR(255) NULL DEFAULT NULL ,
		`BIPMTDUEDT` VARCHAR(255) NULL DEFAULT NULL ,
		`OLDNO` VARCHAR(255) NULL DEFAULT NULL ,
		`COLOR` VARCHAR(255) NULL DEFAULT NULL ,
		`CARDCODE` VARCHAR(255) NULL DEFAULT NULL ,
		PRIMARY KEY (`caseact_id`)
	  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

	ALTER TABLE `cse_caseact` 
	CHANGE COLUMN `TITLE` `TITLE` VARCHAR(255) NULL DEFAULT NULL ;
	ALTER TABLE `cse_caseact` 
	CHANGE COLUMN `COST` `COST` VARCHAR(255) NULL DEFAULT NULL ;
	ALTER TABLE `cse_caseact` 
	CHANGE COLUMN `ACCESS` `ACCESS` VARCHAR(255) NULL DEFAULT NULL ;
	ALTER TABLE `cse_caseact` 
	CHANGE COLUMN `ARAP` `ARAP` VARCHAR(255) NULL DEFAULT NULL ;
	ALTER TABLE `cse_caseact` 
	CHANGE COLUMN `OLE3STYLE` `OLE3STYLE` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `WORDSTYLE` `WORDSTYLE` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `FRMWIDTH` `FRMWIDTH` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `FRMHEIGHT` `FRMHEIGHT` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `FRMTM` `FRMTM` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `FRMBM` `FRMBM` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `FRMLM` `FRMLM` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `FRMRM` `FRMRM` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `ORIENT` `ORIENT` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `COPIES` `COPIES` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `TYPEACT` `TYPEACT` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `BISTYLE` `BISTYLE` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `BIFEE` `BIFEE` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `BICOST` `BICOST` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `BIPMT` `BIPMT` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `BILATEFEE` `BILATEFEE` VARCHAR(255) NULL DEFAULT NULL ;
	ALTER TABLE `cse_caseact` 
	CHANGE COLUMN `BICYCLE` `BICYCLE` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `BITIME` `BITIME` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `BIHOURRATE` `BIHOURRATE` VARCHAR(255) NULL DEFAULT NULL ;
	ALTER TABLE `cse_caseact` 
	CHANGE COLUMN `BIPMTDATE` `BIPMTDATE` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `BIPMTDUEDT` `BIPMTDUEDT` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `OLDNO` `OLDNO` VARCHAR(255) NULL DEFAULT NULL ;
	ALTER TABLE `cse_caseact` 
	CHANGE COLUMN `COLOR` `COLOR` VARCHAR(255) NULL DEFAULT NULL ;
	ALTER TABLE ` cse_`caseact` 
	CHANGE COLUMN `CARDCODE` `CARDCODE` VARCHAR(255) NULL DEFAULT '' ;
	ALTER TABLE `cse_caseact` 
	CHANGE COLUMN `CARDCODE` `CARDCODE` VARCHAR(255) NULL DEFAULT NULL ;
	ALTER TABLE `cse_injury` 
	CHANGE COLUMN `DOR_DATE` `DOR_DATE` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `ADJ1A` `ADJ1A` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `DOI` `DOI` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `DOI2` `DOI2` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `ADJ10A` `ADJ10A` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `S_W` `S_W` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `OTHER_SOL` `OTHER_SOL` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `FOLLOW_UP` `FOLLOW_UP` VARCHAR(255) NULL DEFAULT NULL ,
	CHANGE COLUMN `LIAB` `LIAB` VARCHAR(255) NULL DEFAULT NULL ;
	
	ALTER TABLE `cse_imports` 
	ADD COLUMN `processed` DATETIME NULL DEFAULT '0000-00-00 00:00:00' AFTER `filename`;
	ALTER TABLE `cse_imports` 
	ADD COLUMN `full_filename` VARCHAR(255) NULL DEFAULT '' AFTER `filename`;
	ALTER TABLE `cse_imports` 
	ADD COLUMN `dir` VARCHAR(255) NULL DEFAULT '' AFTER `import_id`;
	
	ALTER TABLE `cse_tasks` 
	ADD INDEX `CASENO` (`CASENO` ASC);
	ALTER TABLE `cse_injury` 
	CHANGE COLUMN `ADJ1E` `ADJ1E` VARCHAR(1050) NULL DEFAULT NULL ;
	
	ALTER TABLE `cse_tivity` 
	ADD COLUMN `flag` VARCHAR(100) NULL DEFAULT '' AFTER `activity_category`;

	ALTER TABLE `cse_doctrk1` 
	ADD INDEX `CASENO` (`CASENO` ASC),
	ADD INDEX `ACTNO` (`ACTNO` ASC);
";
	$stmt = $db->prepare($sql);
	$stmt->execute();
	
	echo "prepped";
	$stmt = null; $db = null;
} catch(PDOException $e) {
	$error = array("error"=> array("text"=>$e->getMessage()));
	echo json_encode($error);
}
include("cls_logging.php");
?>
</body>
</html>